#SERVER-CFG
server:
  port: 1905


#MONGO-CFG
spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost:27017/blogpost
      database: blogpost


#EHCACHE-CFG
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider


 #COLOR-CFG
  output:
    ansi:
      enabled: ALWAYS


#LOGGING-CFG
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG




